/* FORM FUNCTION */
export const ONSUBMIT = "ONSUBMIT"
export const ONCHANGE = "ONCHANGE"
export const ONERRORESPONSE ="ONERRORESPONSE"

/* LOGIN FUNCTION */
export const ONLOGIN = "ONLOGIN"
export const LOGOUT = "LOGOUT"
export const LOGINSUCCESS = "LOGINSUCCESS"
export const LOGINFAILD = "LOGINFAILD";
export const SETCURRENTUSER = "SETCURRENTUSER";
export const VALIDATIONSESSION = "VALIDATIONSESSION"

/* REGISTER*/
export const ONREGISTER      = "ONREGISTER"
export const REGISTERSUCCESS = "REGISTERSUCCESS"
export const REGISTERFAILD   = "REGISTERFAILD"



/* CART CHECKOUT FUNCTION */
export const INCDECREMENTQT = "INCDECREMENTQT";
export const CANCEL = "CANCEL";
export const ADDTOCART = "ADDTOCART";
export const EDITQTPRODUCT = "EDITQTPRODUCT";
export const DELETEPRODUCT = "DELETEPRODUCT";

/* ORDER */


export const LOCATIONSUCCESS = "LOCATIONSUCCESS"
export const LOCATIONFAILED = "FAILEDLOCATION"
export const ONADDORDER = "ONADDORDER"
export const ONSUCCESSORDER = "ONSUCCESSORDER"
export const ONFAIILEDORDER  = "ONSUCCESSORDER"

