export const INCREMENTQT = "INCREMENTQT";
export const DECREMENTQT = "DECREMENTQT";
export const CANCEL = "CANCEL";
export const ADDTOCART = "ADDTOCART";
export const EDITINCQTPRODUCT = "EDITINCQTPRODUCT";
export const EDITDECQTPRODUCT = "EDITDECQTPRODUCT"
export const DELETEPRODUCT ="DELETEPRODUCT"
