export const INCDECREMENTQT = "INCDECREMENTQT";
export const CANCEL = "CANCEL";
export const ADDTOCART = "ADDTOCART";
export const EDITQTPRODUCT = "EDITQTPRODUCT";
export const DELETEPRODUCT ="DELETEPRODUCT"
