export const INCREMENTQT = "INCREMENTQT";
export const DECREMENTQT = "DECREMENTQT";
export const CANCEL = "CANCEL";
export const ADDTOCART = "ADDTOCART";
export const EDITINCQTPRODUCT = "EDITADDQTPRODUCT";
export const EDITDECQTPRODUCT = "EDITADDQTPRODUCT"
export const DELETEPRODUCT ="DELETEPRODUCT"
